/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AAttributevalueAttributevalues extends PAttributevalues
{
    private PAttributevalue _attributevalue_;

    public AAttributevalueAttributevalues()
    {
        // Constructor
    }

    public AAttributevalueAttributevalues(
        @SuppressWarnings("hiding") PAttributevalue _attributevalue_)
    {
        // Constructor
        setAttributevalue(_attributevalue_);

    }

    @Override
    public Object clone()
    {
        return new AAttributevalueAttributevalues(
            cloneNode(this._attributevalue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributevalueAttributevalues(this);
    }

    public PAttributevalue getAttributevalue()
    {
        return this._attributevalue_;
    }

    public void setAttributevalue(PAttributevalue node)
    {
        if(this._attributevalue_ != null)
        {
            this._attributevalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributevalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributevalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributevalue_ == child)
        {
            this._attributevalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributevalue_ == oldChild)
        {
            setAttributevalue((PAttributevalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
