/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AAttribute extends PAttribute
{
    private PAttributename _attributename_;
    private TOpcolon _opcolon_;
    private PAttributevalues _attributevalues_;
    private TOpsemicolon _opsemicolon_;

    public AAttribute()
    {
        // Constructor
    }

    public AAttribute(
        @SuppressWarnings("hiding") PAttributename _attributename_,
        @SuppressWarnings("hiding") TOpcolon _opcolon_,
        @SuppressWarnings("hiding") PAttributevalues _attributevalues_,
        @SuppressWarnings("hiding") TOpsemicolon _opsemicolon_)
    {
        // Constructor
        setAttributename(_attributename_);

        setOpcolon(_opcolon_);

        setAttributevalues(_attributevalues_);

        setOpsemicolon(_opsemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AAttribute(
            cloneNode(this._attributename_),
            cloneNode(this._opcolon_),
            cloneNode(this._attributevalues_),
            cloneNode(this._opsemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttribute(this);
    }

    public PAttributename getAttributename()
    {
        return this._attributename_;
    }

    public void setAttributename(PAttributename node)
    {
        if(this._attributename_ != null)
        {
            this._attributename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributename_ = node;
    }

    public TOpcolon getOpcolon()
    {
        return this._opcolon_;
    }

    public void setOpcolon(TOpcolon node)
    {
        if(this._opcolon_ != null)
        {
            this._opcolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcolon_ = node;
    }

    public PAttributevalues getAttributevalues()
    {
        return this._attributevalues_;
    }

    public void setAttributevalues(PAttributevalues node)
    {
        if(this._attributevalues_ != null)
        {
            this._attributevalues_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributevalues_ = node;
    }

    public TOpsemicolon getOpsemicolon()
    {
        return this._opsemicolon_;
    }

    public void setOpsemicolon(TOpsemicolon node)
    {
        if(this._opsemicolon_ != null)
        {
            this._opsemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opsemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributename_)
            + toString(this._opcolon_)
            + toString(this._attributevalues_)
            + toString(this._opsemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributename_ == child)
        {
            this._attributename_ = null;
            return;
        }

        if(this._opcolon_ == child)
        {
            this._opcolon_ = null;
            return;
        }

        if(this._attributevalues_ == child)
        {
            this._attributevalues_ = null;
            return;
        }

        if(this._opsemicolon_ == child)
        {
            this._opsemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributename_ == oldChild)
        {
            setAttributename((PAttributename) newChild);
            return;
        }

        if(this._opcolon_ == oldChild)
        {
            setOpcolon((TOpcolon) newChild);
            return;
        }

        if(this._attributevalues_ == oldChild)
        {
            setAttributevalues((PAttributevalues) newChild);
            return;
        }

        if(this._opsemicolon_ == oldChild)
        {
            setOpsemicolon((TOpsemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
