/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AAttrlistAttributelist extends PAttributelist
{
    private PAttribute _attribute_;
    private PAttributelist _attributelist_;

    public AAttrlistAttributelist()
    {
        // Constructor
    }

    public AAttrlistAttributelist(
        @SuppressWarnings("hiding") PAttribute _attribute_,
        @SuppressWarnings("hiding") PAttributelist _attributelist_)
    {
        // Constructor
        setAttribute(_attribute_);

        setAttributelist(_attributelist_);

    }

    @Override
    public Object clone()
    {
        return new AAttrlistAttributelist(
            cloneNode(this._attribute_),
            cloneNode(this._attributelist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttrlistAttributelist(this);
    }

    public PAttribute getAttribute()
    {
        return this._attribute_;
    }

    public void setAttribute(PAttribute node)
    {
        if(this._attribute_ != null)
        {
            this._attribute_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attribute_ = node;
    }

    public PAttributelist getAttributelist()
    {
        return this._attributelist_;
    }

    public void setAttributelist(PAttributelist node)
    {
        if(this._attributelist_ != null)
        {
            this._attributelist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributelist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attribute_)
            + toString(this._attributelist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attribute_ == child)
        {
            this._attribute_ = null;
            return;
        }

        if(this._attributelist_ == child)
        {
            this._attributelist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attribute_ == oldChild)
        {
            setAttribute((PAttribute) newChild);
            return;
        }

        if(this._attributelist_ == oldChild)
        {
            setAttributelist((PAttributelist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
