/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class ADisplayDisplayop extends PDisplayop
{
    private TOpleftangle _opleftangle_;

    public ADisplayDisplayop()
    {
        // Constructor
    }

    public ADisplayDisplayop(
        @SuppressWarnings("hiding") TOpleftangle _opleftangle_)
    {
        // Constructor
        setOpleftangle(_opleftangle_);

    }

    @Override
    public Object clone()
    {
        return new ADisplayDisplayop(
            cloneNode(this._opleftangle_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisplayDisplayop(this);
    }

    public TOpleftangle getOpleftangle()
    {
        return this._opleftangle_;
    }

    public void setOpleftangle(TOpleftangle node)
    {
        if(this._opleftangle_ != null)
        {
            this._opleftangle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opleftangle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opleftangle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opleftangle_ == child)
        {
            this._opleftangle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opleftangle_ == oldChild)
        {
            setOpleftangle((TOpleftangle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
