/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AHexcolorvalueAttributevalue extends PAttributevalue
{
    private THexcolor _hexcolor_;

    public AHexcolorvalueAttributevalue()
    {
        // Constructor
    }

    public AHexcolorvalueAttributevalue(
        @SuppressWarnings("hiding") THexcolor _hexcolor_)
    {
        // Constructor
        setHexcolor(_hexcolor_);

    }

    @Override
    public Object clone()
    {
        return new AHexcolorvalueAttributevalue(
            cloneNode(this._hexcolor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHexcolorvalueAttributevalue(this);
    }

    public THexcolor getHexcolor()
    {
        return this._hexcolor_;
    }

    public void setHexcolor(THexcolor node)
    {
        if(this._hexcolor_ != null)
        {
            this._hexcolor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hexcolor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._hexcolor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._hexcolor_ == child)
        {
            this._hexcolor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._hexcolor_ == oldChild)
        {
            setHexcolor((THexcolor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
