/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AImplicitObjectidentifier extends PObjectidentifier
{
    private TDollarsign _dollarsign_;

    public AImplicitObjectidentifier()
    {
        // Constructor
    }

    public AImplicitObjectidentifier(
        @SuppressWarnings("hiding") TDollarsign _dollarsign_)
    {
        // Constructor
        setDollarsign(_dollarsign_);

    }

    @Override
    public Object clone()
    {
        return new AImplicitObjectidentifier(
            cloneNode(this._dollarsign_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImplicitObjectidentifier(this);
    }

    public TDollarsign getDollarsign()
    {
        return this._dollarsign_;
    }

    public void setDollarsign(TDollarsign node)
    {
        if(this._dollarsign_ != null)
        {
            this._dollarsign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dollarsign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dollarsign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dollarsign_ == child)
        {
            this._dollarsign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dollarsign_ == oldChild)
        {
            setDollarsign((TDollarsign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
