/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordclassAttributename extends PAttributename
{
    private TKeywordclass _keywordclass_;

    public AKeywordclassAttributename()
    {
        // Constructor
    }

    public AKeywordclassAttributename(
        @SuppressWarnings("hiding") TKeywordclass _keywordclass_)
    {
        // Constructor
        setKeywordclass(_keywordclass_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordclassAttributename(
            cloneNode(this._keywordclass_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordclassAttributename(this);
    }

    public TKeywordclass getKeywordclass()
    {
        return this._keywordclass_;
    }

    public void setKeywordclass(TKeywordclass node)
    {
        if(this._keywordclass_ != null)
        {
            this._keywordclass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordclass_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordclass_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordclass_ == child)
        {
            this._keywordclass_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordclass_ == oldChild)
        {
            setKeywordclass((TKeywordclass) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
