/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordvalueAttributevalue extends PAttributevalue
{
    private PKeywordclasstype _keywordclasstype_;

    public AKeywordvalueAttributevalue()
    {
        // Constructor
    }

    public AKeywordvalueAttributevalue(
        @SuppressWarnings("hiding") PKeywordclasstype _keywordclasstype_)
    {
        // Constructor
        setKeywordclasstype(_keywordclasstype_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordvalueAttributevalue(
            cloneNode(this._keywordclasstype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordvalueAttributevalue(this);
    }

    public PKeywordclasstype getKeywordclasstype()
    {
        return this._keywordclasstype_;
    }

    public void setKeywordclasstype(PKeywordclasstype node)
    {
        if(this._keywordclasstype_ != null)
        {
            this._keywordclasstype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordclasstype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordclasstype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordclasstype_ == child)
        {
            this._keywordclasstype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordclasstype_ == oldChild)
        {
            setKeywordclasstype((PKeywordclasstype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
