/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordpolyKeywordclasstype extends PKeywordclasstype
{
    private TKeywordpoly _keywordpoly_;

    public AKeywordpolyKeywordclasstype()
    {
        // Constructor
    }

    public AKeywordpolyKeywordclasstype(
        @SuppressWarnings("hiding") TKeywordpoly _keywordpoly_)
    {
        // Constructor
        setKeywordpoly(_keywordpoly_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordpolyKeywordclasstype(
            cloneNode(this._keywordpoly_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordpolyKeywordclasstype(this);
    }

    public TKeywordpoly getKeywordpoly()
    {
        return this._keywordpoly_;
    }

    public void setKeywordpoly(TKeywordpoly node)
    {
        if(this._keywordpoly_ != null)
        {
            this._keywordpoly_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordpoly_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordpoly_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordpoly_ == child)
        {
            this._keywordpoly_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordpoly_ == oldChild)
        {
            setKeywordpoly((TKeywordpoly) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
