/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordborderAttributename extends PAttributename
{
    private TKeywordborder _keywordborder_;

    public AKeywordborderAttributename()
    {
        // Constructor
    }

    public AKeywordborderAttributename(
        @SuppressWarnings("hiding") TKeywordborder _keywordborder_)
    {
        // Constructor
        setKeywordborder(_keywordborder_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordborderAttributename(
            cloneNode(this._keywordborder_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordborderAttributename(this);
    }

    public TKeywordborder getKeywordborder()
    {
        return this._keywordborder_;
    }

    public void setKeywordborder(TKeywordborder node)
    {
        if(this._keywordborder_ != null)
        {
            this._keywordborder_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordborder_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordborder_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordborder_ == child)
        {
            this._keywordborder_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordborder_ == oldChild)
        {
            setKeywordborder((TKeywordborder) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
