/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordrectKeywordclasstype extends PKeywordclasstype
{
    private TKeywordrect _keywordrect_;

    public AKeywordrectKeywordclasstype()
    {
        // Constructor
    }

    public AKeywordrectKeywordclasstype(
        @SuppressWarnings("hiding") TKeywordrect _keywordrect_)
    {
        // Constructor
        setKeywordrect(_keywordrect_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordrectKeywordclasstype(
            cloneNode(this._keywordrect_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordrectKeywordclasstype(this);
    }

    public TKeywordrect getKeywordrect()
    {
        return this._keywordrect_;
    }

    public void setKeywordrect(TKeywordrect node)
    {
        if(this._keywordrect_ != null)
        {
            this._keywordrect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordrect_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordrect_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordrect_ == child)
        {
            this._keywordrect_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordrect_ == oldChild)
        {
            setKeywordrect((TKeywordrect) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
