/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordpositionAttributename extends PAttributename
{
    private TKeywordposition _keywordposition_;

    public AKeywordpositionAttributename()
    {
        // Constructor
    }

    public AKeywordpositionAttributename(
        @SuppressWarnings("hiding") TKeywordposition _keywordposition_)
    {
        // Constructor
        setKeywordposition(_keywordposition_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordpositionAttributename(
            cloneNode(this._keywordposition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordpositionAttributename(this);
    }

    public TKeywordposition getKeywordposition()
    {
        return this._keywordposition_;
    }

    public void setKeywordposition(TKeywordposition node)
    {
        if(this._keywordposition_ != null)
        {
            this._keywordposition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordposition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordposition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordposition_ == child)
        {
            this._keywordposition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordposition_ == oldChild)
        {
            setKeywordposition((TKeywordposition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
