/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AKeywordcolorAttributename extends PAttributename
{
    private TKeywordcolor _keywordcolor_;

    public AKeywordcolorAttributename()
    {
        // Constructor
    }

    public AKeywordcolorAttributename(
        @SuppressWarnings("hiding") TKeywordcolor _keywordcolor_)
    {
        // Constructor
        setKeywordcolor(_keywordcolor_);

    }

    @Override
    public Object clone()
    {
        return new AKeywordcolorAttributename(
            cloneNode(this._keywordcolor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeywordcolorAttributename(this);
    }

    public TKeywordcolor getKeywordcolor()
    {
        return this._keywordcolor_;
    }

    public void setKeywordcolor(TKeywordcolor node)
    {
        if(this._keywordcolor_ != null)
        {
            this._keywordcolor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordcolor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordcolor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordcolor_ == child)
        {
            this._keywordcolor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordcolor_ == oldChild)
        {
            setKeywordcolor((TKeywordcolor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
