/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.node;

import drawlang.analysis.*;

@SuppressWarnings("nls")
public final class AOpsignSign extends PSign
{
    private TOpplus _opplus_;

    public AOpsignSign()
    {
        // Constructor
    }

    public AOpsignSign(
        @SuppressWarnings("hiding") TOpplus _opplus_)
    {
        // Constructor
        setOpplus(_opplus_);

    }

    @Override
    public Object clone()
    {
        return new AOpsignSign(
            cloneNode(this._opplus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpsignSign(this);
    }

    public TOpplus getOpplus()
    {
        return this._opplus_;
    }

    public void setOpplus(TOpplus node)
    {
        if(this._opplus_ != null)
        {
            this._opplus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opplus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opplus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opplus_ == child)
        {
            this._opplus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opplus_ == oldChild)
        {
            setOpplus((TOpplus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
