/* This file was generated by SableCC (http://www.sablecc.org/). */

package drawlang.parser;

import drawlang.node.*;
import drawlang.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTKeywordclass(@SuppressWarnings("unused") TKeywordclass node)
    {
        this.index = 0;
    }

    @Override
    public void caseTKeywordcolor(@SuppressWarnings("unused") TKeywordcolor node)
    {
        this.index = 1;
    }

    @Override
    public void caseTKeywordposition(@SuppressWarnings("unused") TKeywordposition node)
    {
        this.index = 2;
    }

    @Override
    public void caseTKeywordborder(@SuppressWarnings("unused") TKeywordborder node)
    {
        this.index = 3;
    }

    @Override
    public void caseTKeywordsize(@SuppressWarnings("unused") TKeywordsize node)
    {
        this.index = 4;
    }

    @Override
    public void caseTKeywordpoints(@SuppressWarnings("unused") TKeywordpoints node)
    {
        this.index = 5;
    }

    @Override
    public void caseTHexcolor(@SuppressWarnings("unused") THexcolor node)
    {
        this.index = 6;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 7;
    }

    @Override
    public void caseTKeywordcircle(@SuppressWarnings("unused") TKeywordcircle node)
    {
        this.index = 8;
    }

    @Override
    public void caseTKeywordrect(@SuppressWarnings("unused") TKeywordrect node)
    {
        this.index = 9;
    }

    @Override
    public void caseTKeywordpoly(@SuppressWarnings("unused") TKeywordpoly node)
    {
        this.index = 10;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 11;
    }

    @Override
    public void caseTDollarsign(@SuppressWarnings("unused") TDollarsign node)
    {
        this.index = 12;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 13;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 14;
    }

    @Override
    public void caseTLBrk(@SuppressWarnings("unused") TLBrk node)
    {
        this.index = 15;
    }

    @Override
    public void caseTRBrk(@SuppressWarnings("unused") TRBrk node)
    {
        this.index = 16;
    }

    @Override
    public void caseTOpsemicolon(@SuppressWarnings("unused") TOpsemicolon node)
    {
        this.index = 17;
    }

    @Override
    public void caseTOpcolon(@SuppressWarnings("unused") TOpcolon node)
    {
        this.index = 18;
    }

    @Override
    public void caseTOpcomma(@SuppressWarnings("unused") TOpcomma node)
    {
        this.index = 19;
    }

    @Override
    public void caseTOpequal(@SuppressWarnings("unused") TOpequal node)
    {
        this.index = 20;
    }

    @Override
    public void caseTOpplus(@SuppressWarnings("unused") TOpplus node)
    {
        this.index = 21;
    }

    @Override
    public void caseTOpminus(@SuppressWarnings("unused") TOpminus node)
    {
        this.index = 22;
    }

    @Override
    public void caseTOpdot(@SuppressWarnings("unused") TOpdot node)
    {
        this.index = 23;
    }

    @Override
    public void caseTOpleftangle(@SuppressWarnings("unused") TOpleftangle node)
    {
        this.index = 24;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 25;
    }
}
